In [2]:
import pandas as pd

In [6]:
path = r'../scraping_results/'
django_scrap = pd.read_csv(path + 'careerjet_pracuj_django_2023-11-27.csv', index_col = 0)
python_scrap = pd.read_csv(path + 'careerjet_pracuj_python_2023-11-25.csv', index_col = 0)

In [7]:
django_scrap.head()

,title,link,company,location,salary,description,date_added,skills,search_term,date_searched
0,Principal Engineer,careerjet.pl/jobad/ple024624de54a7ab6cd00faaa5...,GlaxoSmithKline,"Poznań, wielkopolskie",NaN,GSK is a global biopharma company with a speci...,NaN,NaN,python,2023-11-27
1,Mid / Senior Embedded C Developer @ Antal Poland,careerjet.pl/jobad/pl61983754038c9fd7fabcf22f3...,Antal International,"Kraków, małopolskie",NaN,"Bardzo dobra znajomość języka programowania C,...",NaN,NaN,python,2023-11-27
2,Senior Data Engineer with Python,careerjet.pl/jobad/plec2c01a7de163b1feea09fbb6...,GFT Technologies,Polska,NaN,You in GFT You will work with and learn from...,NaN,NaN,python,2023-11-27
3,Senior Backend Software Engineer (Python),careerjet.pl/jobad/pl905e92585e2c168426fc9d00d...,Binariks,"Kraków, małopolskie",NaN,Binariks is looking for a highly motivated Sen...,NaN,NaN,python,2023-11-27
4,Software Engineer Graduate/Junior/Mid-level/Se...,careerjet.pl/jobad/pl96d8d973cc51f6d96a07f961d...,Arista Networks,"Kraków, małopolskie",NaN,Company Description Arista Networks was foun...,NaN,NaN,python,2023-11-27

In [8]:
python_scrap.head()

,title,link,company,location,salary,description,date_added,skills,search_term,date_searched
0,Climate Risk - Regulatory Reporting Analyst,careerjet.pl/jobad/plf5c63585be33eed77ba668c07...,Citigroup,"Warszawa, mazowieckie",NaN,As a successful Candidate you will be part of ...,NaN,NaN,python,2023-11-25
1,analityk big data,careerjet.pl/jobad/pla642499eec94e311324e64bbe...,Santander,"Warszawa, mazowieckie",NaN,"analityk big data Country: Poland Czujesz,...",NaN,NaN,python,2023-11-25
2,Software Test Engineer,careerjet.pl/jobad/pl798a9ca8cf8affde11c0eaa00...,Harman,"Łódź, łódzkie",NaN,"HARMAN's engineers and designers are creative,...",NaN,NaN,python,2023-11-25
3,Senior DevOps Engineer,careerjet.pl/jobad/pl3ee93a7b0e2e7e038e538e5e2...,Luxoft,"Wrocław, dolnośląskie",NaN,We identify and implement solutions that empow...,NaN,NaN,python,2023-11-25
4,Senior Test Automation Engineer,careerjet.pl/jobad/pl6c1316b98726ba2a26939895d...,Luxoft,"Warszawa, mazowieckie",NaN,The bank is in process of leading a Digital Tr...,NaN,NaN,python,2023-11-25

In [9]:
print(django_scrap.shape)
print(python_scrap.shape)

(83, 10)
(350, 10)

In [12]:
combined = pd.concat([python_scrap, django_scrap])
combined.shape

(433, 10)